name = "BossDailys SMP pack"
author = "BossDaily"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6efd80c017d505e47e9e088bd840e0688e1440208dc3198b39c6b2acc981588"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
