name = "BossDailys SMP pack"
author = "BossDaily"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74a15574f247e09abfd73ee63701784fa4b64398f54bf6eb90cd269b5b4e8d2e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
