name = "BossDailys SMP pack"
author = "BossDaily"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee943a0538dc5d4daaa69dc7872072485d230544769842b74465e50ac7d2f349"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
