name = "BossDaily's Modpack"
author = "BossDaily"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a25f9ab45a5f740635b95e8b909b2fbe6845d4e9e64dc54c20f91142b1af8b6a"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
