name = "BossDailys Modpack"
author = "BossDaily"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8ed1f36bfcea2c5fd4757c88703c204e93f394d25df2bf1fdea75872d47a934"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
