name = "BossDailys Modpack"
author = "BossDaily"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "794b9cd195bef763ff9e8488df03d24cc6a2c3fbdf54530dfbc5d094dc1d9574"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
