name = "BossDaily's Modpack"
author = "BossDaily"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c04230e39922f84bf58b186fddee5c39d65060015ee92498937f977abf353d57"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
