name = "BossDailys Modpack"
author = "BossDaily"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef340e633ef6cd20fbf31bb54b88ee7ea4bae20800c11e7197b9501edf852ea"

[versions]
fabric = "0.14.6"
minecraft = "1.19"
