name = "BossDaily's Modpack v2"
author = "BossDaily"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a84dd4a02835e05cb7ba6c4b3fe58455d70fd3a78776b5657add6c5be59385f8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
