name = "AntiGhost"
filename = "antighost-1.18-fabric0.43.1-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/423/antighost-1.18-fabric0.43.1-1.1.4.jar"
hash-format = "sha1"
hash = "619e250c133106bacc3e3b560839bd4b324dfda8"

[update]
[update.curseforge]
file-id = 3543423
project-id = 273279
