name = "ARRP"
filename = "arrp-0.5.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3529/149/arrp-0.5.4.jar"
hash-format = "sha1"
hash = "288124e89e8b3f7bb9f67b49a085f2c0d55a2439"

[update]
[update.curseforge]
file-id = 3529149
project-id = 463113
