name = "Better Mount HUD"
filename = "bettermounthud-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/536/bettermounthud-1.1.4.jar"
hash-format = "sha1"
hash = "60035cc1e9cf8bf880c42f57427719d773df5cd5"

[update]
[update.curseforge]
file-id = 3637536
project-id = 475358
