name = "Borderless Mining"
filename = "borderless-mining-1.1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/245/borderless-mining-1.1.1+1.18.jar"
hash-format = "sha1"
hash = "0fe49bcdb499f7cd68bf5666e5893bfa7edd04ee"

[update]
[update.curseforge]
file-id = 3549245
project-id = 310205
