name = "CIT Resewn"
filename = "CITResewn-0.9.1+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/263/CITResewn-0.9.1+1.18.1.jar"
hash-format = "sha1"
hash = "a320fbe1f0f6c1364c6afb224f993ba4252e6206"

[update]
[update.curseforge]
file-id = 3609263
project-id = 521427
