name = "Cloth API (Fabric)"
filename = "cloth-api-3.1.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/123/cloth-api-3.1.61.jar"
hash-format = "sha1"
hash = "089d6e5e937b5b58d0fb62e10b9cb26919bfe75e"

[update]
[update.curseforge]
file-id = 3612123
project-id = 317121
