name = "Colormatic"
filename = "colormatic-3.1.0+mc.1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/601/colormatic-3.1.0+mc.1.18.1.jar"
hash-format = "sha1"
hash = "7357a0a45aa4d00d06f52ba9cee643869ae25e40"

[update]
[update.curseforge]
file-id = 3654601
project-id = 325092
