name = "CompleteConfig"
filename = "completeconfig-lib-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/13/completeconfig-lib-1.3.3.jar"
hash-format = "sha1"
hash = "bdf33e87d89872fd0c2b6992cd467c6777e75e42"

[update]
[update.curseforge]
file-id = 3555013
project-id = 381257
