name = "Continuity"
filename = "continuity-1.1.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3655/794/continuity-1.1.0+1.18.jar"
hash-format = "sha1"
hash = "2bb59162457f3fbe90794c1a8cf3ca9e199e268e"

[update]
[update.curseforge]
file-id = 3655794
project-id = 531351
