name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-1.18+_2.5.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/590/entity-texture-features-1.18+_2.5.8.jar"
hash-format = "sha1"
hash = "bddbe97012700046d110d5768a90db78be2a2de0"

[update]
[update.curseforge]
file-id = 3704590
project-id = 568563
