name = "Entity Texture Features (Random & Emissive Mob Textures!) - [FABRIC - 1.16+]"
filename = "entity-texture-features-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/758/entity-texture-features-2.2.0.jar"
hash-format = "sha1"
hash = "cf8c14f8d1134040377b9e11bba02e316c08a338"

[update]
[update.curseforge]
file-id = 3654758
project-id = 568563
