name = "Entity Texture Features - [Fabric]"
filename = "entity-texture-features-[1.18.0-1]-2.4.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/631/entity-texture-features-%5B1.18.0-1%5D-2.4.5.jar"
hash-format = "sha1"
hash = "beef847991cff76d48cfe0c7f7f495390062480b"

[update]
[update.curseforge]
file-id = 3683631
project-id = 568563
