name = "Fabrishot"
filename = "fabrishot-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/13/fabrishot-1.7.0.jar"
hash-format = "sha1"
hash = "343f31455c666b3979026d8a983abfa9c8ca0c9e"

[update]
[update.curseforge]
file-id = 3672013
project-id = 404870
