name = "Fabric API"
filename = "fabric-api-0.46.4+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3634/318/fabric-api-0.46.4+1.18.jar"
hash-format = "sha1"
hash = "23859ea5555187d5f95441815929ab5b3b53f8fe"

[update]
[update.curseforge]
file-id = 3634318
project-id = 306612
