name = "Fabric Bedrock Miner"
filename = "bedrock-miner-1.0.0-for-minecraft-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3607/8/bedrock-miner-1.0.0-for-minecraft-1.18.1.jar"
hash-format = "sha1"
hash = "d9bd0914e0e8d7ac48dfb0672f50a7fa0972a769"

[update]
[update.curseforge]
file-id = 3607008
project-id = 523864
