name = "Fabrishot"
filename = "fabrishot-1.6.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/125/fabrishot-1.6.2.jar"
hash-format = "sha1"
hash = "b3385f37c464a619637ab4dbb49382553b8bf8d3"

[update]
[update.curseforge]
file-id = 3637125
project-id = 404870
