name = "Fabric Bedrock Miner"
filename = "bedrock-miner-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/828/bedrock-miner-1.0.0.jar"
hash-format = "sha1"
hash = "3b4dd06d87d95cae9db0f266300b354611b89662"

[update]
[update.curseforge]
file-id = 3683828
project-id = 523864
