name = "FastChest"
filename = "fast-chest-1.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/190/fast-chest-1.2+1.18.jar"
hash-format = "sha1"
hash = "92655599396787d5ea4c4e66a4ea2f5779584abc"

[update]
[update.curseforge]
file-id = 3544190
project-id = 436038
