name = "Iris Shaders"
filename = "iris-mc1.18.1-1.2.0-pre.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/857/iris-mc1.18.1-1.2.0-pre.jar"
hash-format = "sha1"
hash = "94c66f904514e1a7e0ad106542a693e09b603044"

[update]
[update.curseforge]
file-id = 3612857
project-id = 455508
