name = "Item Model Fix (Fabric)"
filename = "item-model-fix-1.0.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3573/935/item-model-fix-1.0.3+1.18.jar"
hash-format = "sha1"
hash = "2aa679f2dc887e2ce45d55fffe67af36250b4841"

[update]
[update.curseforge]
file-id = 3573935
project-id = 399798
