name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/228/lambdabettergrass-1.2.3+1.18.jar"
hash-format = "sha1"
hash = "7f722205950dadc03beef72abbbba2ed2bcf767b"

[update]
[update.curseforge]
file-id = 3684228
project-id = 400322
