name = "Language Reload"
filename = "language-reload-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/52/language-reload-1.2.1.jar"
hash-format = "sha1"
hash = "4fc9f67f810bbe4a0958999c6eda9c7ebfd1b797"

[update]
[update.curseforge]
file-id = 3641052
project-id = 527334
