name = "MidnightLib"
filename = "midnightlib-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3657/92/midnightlib-0.4.0.jar"
hash-format = "sha1"
hash = "bad7a3239314c297a1793b96a8688ba71b0b928e"

[update]
[update.curseforge]
file-id = 3657092
project-id = 488090
