name = "More Chat History"
filename = "morechathistory-1.18-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/709/morechathistory-1.18-1.1.0.jar"
hash-format = "sha1"
hash = "378a6a5b02f45feff9d55b28be55d36474fca77f"

[update]
[update.curseforge]
file-id = 3545709
project-id = 518319
