name = "No Fade"
filename = "nofade-1.18-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/935/nofade-1.18-2.0.1.jar"
hash-format = "sha1"
hash = "76951fe09b742ba0ca07acc7c54e4c3760157071"

[update]
[update.curseforge]
file-id = 3550935
project-id = 452768
