name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.1.4+1.18.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/828/notenoughcrashes-4.1.4+1.18.1-fabric.jar"
hash-format = "sha1"
hash = "a6b83e46b3a8b1884f539683042686680729ce2a"

[update]
[update.curseforge]
file-id = 3606828
project-id = 353890
