name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18.1-1.2.10.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18-1.2.10/plasmovoice-fabric-1.18.1-1.2.10.jar"
hash-format = "sha1"
hash = "513bead73c6790869fff03591faa8ba0de5bbfea"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "GDqzd1zx"
