name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18.2-1.2.11-hotfix1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18.2-1.2.11/plasmovoice-fabric-1.18.2-1.2.11-hotfix1.jar"
hash-format = "sha1"
hash = "f8635d3a560b2c6cd71a89a2ef83bf1c96abb1fc"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "Lwy2apRP"
