name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18-1.2.13.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18-1.2.13/plasmovoice-fabric-1.18-1.2.13.jar"
hash-format = "sha1"
hash = "6fd2d3fd1464218aecb387d04a8b51ad07ffc159"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "CGqrbEX7"
