name = "Puzzle"
filename = "puzzle-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3697/550/puzzle-1.2.1.jar"
hash-format = "sha1"
hash = "be946b8c5a8b5499b18b89fdf3c14c8c708b056f"

[update]
[update.curseforge]
file-id = 3697550
project-id = 563977
