name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.18.1-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/245/reeses_sodium_options-mc1.18.1-1.4.0.jar"
hash-format = "sha1"
hash = "417389dd15f5f1f84ed9c8479264d09f99742498"

[update]
[update.curseforge]
file-id = 3622245
project-id = 511319
