name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.18.2-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/685/reeses_sodium_options-mc1.18.2-1.4.1.jar"
hash-format = "sha1"
hash = "7a4cfadb624efcaa56561bfa5f1cdeeafb265a13"

[update]
[update.curseforge]
file-id = 3669685
project-id = 511319
