name = "Simple Discord RPC [Forge/Fabric]"
filename = "simple-rpc-fabric-1.18.2-2.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/228/simple-rpc-fabric-1.18.2-2.7.3.jar"
hash-format = "sha1"
hash = "0c00df21846d65dba67e2893eafbf283a7955499"

[update]
[update.curseforge]
file-id = 3670228
project-id = 411816
