name = "Sodium Extra"
filename = "sodium-extra-mc1.18.1-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/95/sodium-extra-mc1.18.1-0.4.0.jar"
hash-format = "sha1"
hash = "0a5e52d66faf9ba68cec2d732b72557173a990a0"

[update]
[update.curseforge]
file-id = 3652095
project-id = 447673
