name = "Starlight (Fabric)"
filename = "starlight-1.0.0+fabric.d0a3220.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/912/starlight-1.0.0+fabric.d0a3220.jar"
hash-format = "sha1"
hash = "743b14918588186cae2117d1a9684b400939e6f8"

[update]
[update.curseforge]
file-id = 3554912
project-id = 521783
