name = "TieFix"
filename = "TieFix-1.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/238/TieFix-1.9.0.jar"
hash-format = "sha1"
hash = "dc07b38ae4c4b4788851d852f51970d65103a01f"

[update]
[update.curseforge]
file-id = 3625238
project-id = 560957
