name = "ToolTipFix"
filename = "tooltipfix-1.0.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/273/tooltipfix-1.0.4-1.18.jar"
hash-format = "sha1"
hash = "16b844c45ce0e4f1159ff51739479e8747a64d84"

[update]
[update.curseforge]
file-id = 3543273
project-id = 411557
