name = "Tweakeroo"
filename = "tweakeroo-fabric-1.18.1-0.12.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3643/79/tweakeroo-fabric-1.18.1-0.12.3.jar"
hash-format = "sha1"
hash = "05726e822038e1fed0e4abea7f48b9be7016099f"

[update]
[update.curseforge]
file-id = 3643079
project-id = 297344
